// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jizqudnounnxwwhyfjxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppenF1ZG5vdW5ueHd3aHlmanhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzY0ODgsImV4cCI6MjA2NjQxMjQ4OH0.4gdrvTBrq1QfSCf4Yuurz8G7y-LIXLSSli7CILPtkK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});